project_name: "argocd-env-plugin"

builds:
  - binary: "argocd-env-plugin"
    flags: "-trimpath"
    ldflags: >-
      -s -w
      -X "github.com/s-starostin/argocd-env-plugin/version.Version={{.Tag}}"
      -X "github.com/s-starostin/argocd-env-plugin/version.BuildDate={{.Date}}"
      -X "github.com/s-starostin/argocd-env-plugin/version.CommitSHA={{.Commit}}"
    env:
      - "CGO_ENABLED=0"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    tags:
      - netgo
      - static_build

archives:
  - format: binary

changelog:
  skip: true
